apiVersion: apps/v1 # for kubectl versions >= 1.9.0 use apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-deployment-d09
  template:
    metadata:
      labels:
        app: my-deployment-d09
    spec:
      containers:
      - name: my-pod
        image: chu16537/docker-demo:latest
        ports:
        - containerPort: 3000

