# Node 的 /tmp 掛在 apiserver 的 /tmp 下
# 當 apiserver 的 /tmp 新增檔案時，可以從 Node 的 /tmp 中底下找到該檔案，因為兩者存取相同的資源。
apiVersion: v1
kind: Pod
metadata:
    name: apiserver
spec:
    containers:
        - name: apiserver
          image: chu16537/docker-demo
          volumeMounts:
              - mountPath: /tmp
                name: tmp-volume
          imagePullPolicy: Always
    volumes:
        - name: tmp-volume
          hostPath:
              path: /tmp
              type: Directory
