apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: horizontal-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: horizontal-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 5 #(%(單位)  根據值 spec.template.spec.containers.resources.requests.cpu )


  
