apiVersion: v1
kind: Pod
metadata:
    name: my-pod-with-mounting-secret-d12
    labels:
        app: webserver
spec:
    containers:
        - name: demo-pod-d12
          image: chu16537/docker-demo
          ports:
              - containerPort: 3000
          volumeMounts:
              - name: secret-volume
                # exec後 的存放路徑
                mountPath: /etc/creds
                readOnly: true
    volumes:
        - name: secret-volume
          secret:
              secretName: demo-secret-from-yaml-d12
