apiVersion: apps/v1 # for kubectl versions >= 1.9.0 use apps/v1
kind: Deployment
metadata:
  name: hello-deployment-d11
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-deployment-d11
  template:
    metadata:
      labels:
        app: my-deployment-d11
    spec:
      containers:
      - name: webapp
        image: chu16537/docker-demo:latest
        ports:
        - name: webapp-port
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: webapp-port
            # 設定當 service 剛啟動時，要延遲幾秒再開始做 health check
          initialDelaySeconds: 15
          # 代表每隔幾秒訪問一次，預設值為 10秒
          periodSeconds: 15
          timeoutSeconds: 30  
          # 可以設置訪問幾次就代表目前 service 還正常運行
          successThreshold: 1
          # 會嘗試的次數
          failureThreshold: 3

