apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret-d13
type: Opaque
data: 
  # wordpress: 4-php7.0 跟 latest 的  wp-config.php 設定不一樣

  # echo -n "rootpass" | base64
  db-password: cm9vdHBhc3M=



