apiVersion: v1
kind: Pod
metadata:
  name: pod-name
  labels:
    app: webserver
spec:
  containers:
  - name: pod-container-name
    image: chu16537/docker-demo
    ports:
    - containerPort: 3000
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: secret-from-yaml
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-from-yaml
          key: password
