apiVersion: v1
kind: ReplicationController
metadata:
    name: my-replication-controller-d07
spec:
    # pod 數量
    replicas: 3
    selector:
        app: hello-pod-v1-d07
    template:
        metadata:
            labels:
            # 必須跟 selector.app 一樣
                app: hello-pod-v1-d07
                version: v1
        spec:
            containers:
                - name: my-pod-d07
                  image: chu16537/docker-demo
                  ports:
                      - containerPort: 3000
    #  如果使用本地docker image 記得加上
    # imagePullPolicy: Never
    # restartPolicy: Never
